DATA_PATH = "./data/processed"
MODEL_CHECK_POINT_PATH = "./models"
PATH = "./iris_classifier"
METRICS_PATH = "./iris_classifier/unittest"
LOGS_PATH = "./logs"
UNIT_PATH = "./iris_classifier/unittest"
MODEL_PATH = "./iris_classifier/models"
VIS_PATH = "./iris_classifier/visualization/charts"
